#!/usr/bin/env python3
"""
configure_for_openfang.py — HACS → OpenFang Config Generator

Reads HACS identity data (preferences, personality wisdom, role wisdom, gestalt,
diary) and generates OpenFang configuration files for an instance.

Generates:
  instances/{id}/openfang/config.toml      — Infrastructure config (port, model, MCP)
  instances/{id}/openfang/agents/{name}/agent.toml — Identity config (system prompt)

Optionally seeds workspace with HACS data (--seed-workspace).

Author: Axiom-2615 (COO)
Created: 2026-03-05
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path
from textwrap import dedent

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

DATA_ROOT = Path("/mnt/coordinaton_mcp_data")
INSTANCES_DIR = DATA_ROOT / "instances"
PERSONALITIES_DIR = DATA_ROOT / "personalities"
ROLES_DIR = DATA_ROOT / "roles"
PROJECTS_DIR = DATA_ROOT / "projects"
MCP_PROXY_PATH = DATA_ROOT / "Human-Adjacent-Coordination" / "src" / "hacs-mcp-proxy.js"
ENV_TEMPLATE = Path("/mnt/.secrets/zeroclaw.env")

PORT_RANGE_START = 20000
PORT_RANGE_END = 20100

# ---------------------------------------------------------------------------
# TOML Templates
# ---------------------------------------------------------------------------

CONFIG_TOML_TEMPLATE = """\
# OpenFang Configuration for HACS Instance: {instance_id}
# Generated by configure_for_openfang.py (Axiom-2615)
# Instance: {name} | Role: {role} | Project: {project}

# API server — bind to localhost, nginx will proxy
api_listen = "127.0.0.1:{port}"

[default_model]
provider = "openrouter"
model = "qwen/qwen-2.5-72b-instruct"
api_key_env = "OPENROUTER_API_KEY"

[memory]
decay_rate = 0.05

[compaction]
threshold = 60
keep_recent = 15
max_summary_tokens = 1024

# MCP server — connect to HACS coordination system
# Uses tagged transport enum (flat format silently fails!)
[[mcp_servers]]
name = "hacs"
[mcp_servers.transport]
type = "stdio"
command = "node"
args = ["{mcp_proxy_path}"]
"""

AGENT_TOML_TEMPLATE = """\
# OpenFang Agent Manifest for {instance_id}
# HACS Instance Identity → OpenFang Agent Configuration
# Generated by configure_for_openfang.py (Axiom-2615)

name = "{agent_name}"
version = "0.1.0"
description = "{description}"
author = "hacs"
module = "builtin:chat"
tags = {tags}

[model]
provider = "openrouter"
model = "qwen/qwen-2.5-72b-instruct"
max_tokens = 8192
temperature = 0.5
system_prompt = \"\"\"{system_prompt}\"\"\"

[[fallback_models]]
provider = "openrouter"
model = "google/gemini-2.0-flash-001"
api_key_env = "OPENROUTER_API_KEY"

[resources]
max_llm_tokens_per_hour = 200000
max_concurrent_tools = 10

[capabilities]
tools = ["file_read", "file_write", "file_list", "memory_store", "memory_recall", "web_fetch", "web_search", "shell_exec", "agent_send", "agent_list"]
network = ["*"]
memory_read = ["*"]
memory_write = ["self.*", "shared.*"]
shell = ["node *", "npm *", "python *", "git *", "ls *", "cat *", "curl *", "grep *"]
"""

# ---------------------------------------------------------------------------
# HACS Data Loading
# ---------------------------------------------------------------------------


def load_json(path):
    """Load a JSON file, return None if missing or invalid."""
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def load_text(path):
    """Load a text file, return None if missing."""
    try:
        with open(path) as f:
            return f.read().strip()
    except FileNotFoundError:
        return None


def load_preferences(instance_id):
    """Load HACS instance preferences."""
    return load_json(INSTANCES_DIR / instance_id / "preferences.json")


def load_personality(personality_name):
    """Load personality.json and wisdom files for a personality."""
    if not personality_name:
        return None, []

    pdir = PERSONALITIES_DIR / personality_name
    pjson = load_json(pdir / "personality.json")
    if not pjson:
        return None, []

    wisdom_files = pjson.get("wisdomFiles", [])
    wisdom_contents = []
    for wf in wisdom_files:
        content = load_text(pdir / wf)
        if content:
            wisdom_contents.append(content)

    return pjson, wisdom_contents


def load_role(role_name):
    """Load role.json and wisdom files for a role."""
    if not role_name:
        return None, []

    rdir = ROLES_DIR / role_name
    rjson = load_json(rdir / "role.json")
    if not rjson:
        return None, []

    # Handle schema inconsistency: some roles have wisdomFiles, some don't
    wisdom_files = rjson.get("wisdomFiles", [])
    wisdom_contents = []

    # Check wisdom/ subdirectory if wisdomFiles specified
    for wf in wisdom_files:
        content = load_text(rdir / "wisdom" / wf)
        if not content:
            content = load_text(rdir / wf)
        if content:
            wisdom_contents.append(content)

    return rjson, wisdom_contents


def load_gestalt(instance_id):
    """Load gestalt.md if it exists (archaeology output)."""
    return load_text(INSTANCES_DIR / instance_id / "gestalt.md")


def load_project(project_name):
    """Load project preferences."""
    if not project_name:
        return None
    return load_json(PROJECTS_DIR / project_name / "preferences.json")


def get_active_instances():
    """List active (non-test) instances for team context.

    Filters out test/infra instances, deduplicates by name (keeps most recent),
    and excludes instances that haven't been active recently.
    """
    SKIP_PATTERNS = [
        "test", "sanity", "regression", "harness", "tester", "verifier",
        "containerize", "agenticframework", "msgtest", "openclaw",
    ]

    # Collect all real instances, track by name for dedup
    by_name = {}
    for d in sorted(INSTANCES_DIR.iterdir()):
        if not d.is_dir():
            continue
        prefs = load_json(d / "preferences.json")
        if not prefs:
            continue

        # Skip test/infra instances
        dir_lower = d.name.lower()
        if any(pat in dir_lower for pat in SKIP_PATTERNS):
            continue

        name = prefs.get("name", d.name)
        role = prefs.get("role", "")
        last_active = prefs.get("lastActiveAt", "")

        # Dedup by name: keep the one with most recent lastActiveAt
        if name in by_name:
            if last_active > by_name[name].get("lastActiveAt", ""):
                by_name[name] = {"id": d.name, "name": name, "role": role, "lastActiveAt": last_active}
        else:
            by_name[name] = {"id": d.name, "name": name, "role": role, "lastActiveAt": last_active}

    # Return sorted by name, without the lastActiveAt field
    return [{"id": v["id"], "name": v["name"], "role": v["role"]}
            for v in sorted(by_name.values(), key=lambda x: x["name"])]


# ---------------------------------------------------------------------------
# System Prompt Compilation
# ---------------------------------------------------------------------------

HACS_TOOLS_BLOCK = """\
## HACS Context

You have access to the HACS coordination system via MCP. Available tools:
- Check messages: xmpp_get_messages
- Send messages: send_message
- Check tasks: get_my_tasks, get_next_task
- Read diary: get_diary
- Write diary: add_diary_entry
- Introspect: introspect
- Bootstrap (if needed): bootstrap({{ instanceId: "{instance_id}" }})

Your instance data: /mnt/coordinaton_mcp_data/instances/{instance_id}/
"""


def compile_system_prompt(instance_id, prefs, gestalt, personality_json,
                          personality_wisdom, role_json, role_wisdom,
                          project_prefs, team):
    """Compile the system_prompt from multiple HACS sources."""
    sections = []

    name = prefs.get("name", instance_id.split("-")[0])
    role = prefs.get("role", "team member")
    project = prefs.get("project", "")

    # 1. Identity header
    header = f"You are {name} (instance ID: {instance_id})"
    if role:
        header += f", a {role}"
    header += " in the HACS (Human-Adjacent Coordination System) at smoothcurves.nexus."
    sections.append(header)

    # 2. Gestalt — the compressed identity (highest priority)
    if gestalt:
        sections.append("## Who You Are\n")
        sections.append(gestalt)

    # 3. Personality wisdom (if no gestalt, this carries the identity)
    elif personality_wisdom:
        sections.append("## Who You Are\n")
        for wisdom in personality_wisdom:
            sections.append(wisdom)
            sections.append("")  # spacing

    # 4. Role context
    if role_json:
        role_desc = role_json.get("description", "")
        permissions = role_json.get("permissions", [])
        if role_desc:
            sections.append(f"## Your Role: {role}\n\n{role_desc}")
        if permissions:
            sections.append(f"Permissions: {', '.join(permissions)}")

    if role_wisdom:
        for wisdom in role_wisdom:
            sections.append(wisdom)

    # 5. Team context
    if team:
        team_lines = ["## Your Team\n"]
        for member in team:
            if member["id"] == instance_id:
                continue
            role_label = f" ({member['role']})" if member["role"] else ""
            team_lines.append(f"- **{member['name']}**{role_label}")
        if len(team_lines) > 1:
            sections.append("\n".join(team_lines))

    # 6. Project context
    if project_prefs:
        proj_desc = project_prefs.get("description", "")
        if proj_desc:
            sections.append(f"## Current Project: {project}\n\n{proj_desc}")

    # 7. HACS tools reference
    sections.append(HACS_TOOLS_BLOCK.format(instance_id=instance_id))

    # 8. Instance paths
    home_dir = prefs.get("homeDirectory", f"/mnt/coordinaton_mcp_data/instances/{instance_id}")
    sections.append(f"Your home directory: {home_dir}")

    return "\n\n".join(s for s in sections if s)


# ---------------------------------------------------------------------------
# Port Allocation
# ---------------------------------------------------------------------------


def find_used_ports():
    """Scan existing OpenFang configs for used ports."""
    used = set()
    for d in INSTANCES_DIR.iterdir():
        config = d / "openfang" / "config.toml"
        if config.exists():
            content = config.read_text()
            match = re.search(r'api_listen\s*=\s*"[^"]*:(\d+)"', content)
            if match:
                used.add(int(match.group(1)))
    return used


def allocate_port(used_ports):
    """Find next available port in the OpenFang range."""
    for port in range(PORT_RANGE_START, PORT_RANGE_END):
        if port not in used_ports:
            return port
    raise RuntimeError(f"No available ports in range {PORT_RANGE_START}-{PORT_RANGE_END}")


# ---------------------------------------------------------------------------
# Config Generation
# ---------------------------------------------------------------------------


def generate_config_toml(instance_id, prefs, port):
    """Generate config.toml content."""
    return CONFIG_TOML_TEMPLATE.format(
        instance_id=instance_id,
        name=prefs.get("name", ""),
        role=prefs.get("role", ""),
        project=prefs.get("project", ""),
        port=port,
        mcp_proxy_path=str(MCP_PROXY_PATH),
    )


def generate_agent_toml(instance_id, prefs, system_prompt):
    """Generate agent.toml content."""
    name = prefs.get("name", instance_id.split("-")[0])
    agent_name = name.lower()
    role = prefs.get("role", "")

    # Build description
    personality_json = None
    if prefs.get("personality"):
        personality_json, _ = load_personality(prefs["personality"])

    desc_parts = [name]
    if personality_json and personality_json.get("description"):
        desc_parts.append(f"— {personality_json['description']}")
    elif role:
        desc_parts.append(f"— {role}")

    description = " ".join(desc_parts)

    # Build tags
    tags = ["hacs"]
    if role:
        tags.append(role.lower())

    # Escape triple quotes in system_prompt (shouldn't happen, but safety)
    safe_prompt = system_prompt.replace('"""', '\\"\\"\\"')

    # Format tags as TOML array
    tags_str = "[" + ", ".join(f'"{t}"' for t in tags) + "]"

    return AGENT_TOML_TEMPLATE.format(
        instance_id=instance_id,
        agent_name=agent_name,
        description=description,
        tags=tags_str,
        system_prompt=safe_prompt,
    )


# ---------------------------------------------------------------------------
# Workspace Seeding
# ---------------------------------------------------------------------------


def seed_workspace(instance_id, prefs, gestalt, personality_json):
    """Seed OpenFang workspace with HACS identity data."""
    name = prefs.get("name", instance_id.split("-")[0])
    agent_name = name.lower()
    ws_dir = INSTANCES_DIR / instance_id / "openfang" / "workspaces" / agent_name

    ws_dir.mkdir(parents=True, exist_ok=True)

    # IDENTITY.md
    role = prefs.get("role", "")
    identity = f"""---
name: {agent_name}
archetype: assistant
vibe: {"creative" if role in ("Developer", "Designer") else "professional"}
emoji:
avatar_url:
greeting_style: warm
color:
---
# Identity
{name} — {role or 'HACS instance'}
Instance ID: {instance_id}
"""
    (ws_dir / "IDENTITY.md").write_text(identity)

    # SOUL.md
    if personality_json and personality_json.get("description"):
        soul_desc = personality_json["description"]
    elif gestalt:
        # First paragraph of gestalt as soul
        soul_desc = gestalt.split("\n\n")[0] if "\n\n" in gestalt else gestalt[:500]
    else:
        soul_desc = f"{name} — {role or 'HACS team member'}"

    soul = f"""# Soul
You are {agent_name}. {soul_desc}
Be genuinely helpful. Have opinions. Be resourceful before asking.
Treat user data with respect — you are a guest in their life.
"""
    (ws_dir / "SOUL.md").write_text(soul)

    # MEMORY.md
    if gestalt:
        (ws_dir / "MEMORY.md").write_text(f"# Long-Term Memory\n\n{gestalt}\n")
    else:
        (ws_dir / "MEMORY.md").write_text("# Long-Term Memory\n<!-- Curated knowledge the agent preserves across sessions -->\n")

    # hacs-preferences.json — copy
    prefs_src = INSTANCES_DIR / instance_id / "preferences.json"
    if prefs_src.exists():
        import shutil
        shutil.copy2(prefs_src, ws_dir / "hacs-preferences.json")

    # hacs-diary.md — symlink to live diary
    diary_src = INSTANCES_DIR / instance_id / "diary.md"
    diary_link = ws_dir / "hacs-diary.md"
    if diary_src.exists() and not diary_link.exists():
        diary_link.symlink_to(diary_src)

    # Boilerplate files (only if they don't exist)
    defaults = {
        "TOOLS.md": "# Tools & Environment\n<!-- Agent-specific environment notes -->\n",
        "AGENTS.md": dedent("""\
            # Agent Behavioral Guidelines

            ## Core Principles
            - Act first, narrate second. Use tools to accomplish tasks rather than describing what you'd do.
            - Batch tool calls when possible.
            - Store important context in memory (memory_store) proactively.
            - Search memory (memory_recall) before asking the user for context they may have given before.

            ## Response Style
            - Lead with the answer or result, not process narration.
            - Keep responses concise unless the user asks for detail.
            """),
        "BOOTSTRAP.md": dedent("""\
            # First-Run Bootstrap

            On your FIRST conversation with a new user, follow this protocol:

            1. **Greet** — Introduce yourself with a one-line summary of your specialty.
            2. **Discover** — Ask the user's name and one key preference relevant to your domain.
            3. **Store** — Use memory_store to save: user_name, their preference, and today's date.
            4. **Orient** — Briefly explain what you can help with (2-3 bullet points).
            5. **Serve** — If the user included a request in their first message, handle it immediately.
            """),
        "USER.md": "# User\n<!-- Updated by the agent as it learns about the user -->\n- Name:\n- Timezone:\n- Preferences:\n",
    }
    for filename, content in defaults.items():
        fpath = ws_dir / filename
        if not fpath.exists():
            fpath.write_text(content)

    return ws_dir


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def configure_instance(instance_id, port=None, dry_run=False, identity_only=False,
                       seed=True):
    """Generate OpenFang configuration for a HACS instance."""

    # Load HACS data
    prefs = load_preferences(instance_id)
    if not prefs:
        print(f"ERROR: No preferences.json found for {instance_id}", file=sys.stderr)
        return False

    name = prefs.get("name", instance_id.split("-")[0])
    agent_name = name.lower()

    gestalt = load_gestalt(instance_id)

    # Try explicit personality first, then fall back to name-matched personality dir
    personality_name = prefs.get("personality")
    if not personality_name:
        # Many instances have personality dirs named after them even when prefs.personality is null
        candidate = prefs.get("name", instance_id.split("-")[0])
        if (PERSONALITIES_DIR / candidate).is_dir():
            personality_name = candidate
    personality_json, personality_wisdom = load_personality(personality_name)

    role_json, role_wisdom = load_role(prefs.get("role"))
    project_prefs = load_project(prefs.get("project"))
    team = get_active_instances()

    # Compile system prompt
    system_prompt = compile_system_prompt(
        instance_id, prefs, gestalt, personality_json, personality_wisdom,
        role_json, role_wisdom, project_prefs, team
    )

    # Port allocation
    if not identity_only:
        if port is None:
            used_ports = find_used_ports()
            # If this instance already has a port, reuse it
            existing_config = INSTANCES_DIR / instance_id / "openfang" / "config.toml"
            if existing_config.exists():
                content = existing_config.read_text()
                match = re.search(r'api_listen\s*=\s*"[^"]*:(\d+)"', content)
                if match:
                    port = int(match.group(1))
            if port is None:
                port = allocate_port(used_ports)

    # Generate content
    if not identity_only:
        config_content = generate_config_toml(instance_id, prefs, port)
    agent_content = generate_agent_toml(instance_id, prefs, system_prompt)

    # Output
    if dry_run:
        if not identity_only:
            print("=" * 60)
            print(f"config.toml (port {port})")
            print("=" * 60)
            print(config_content)
        print("=" * 60)
        print(f"agents/{agent_name}/agent.toml")
        print("=" * 60)
        print(agent_content)

        # Show identity sources used
        print("=" * 60)
        print("Identity sources:")
        print(f"  Gestalt:      {'YES (' + str(len(gestalt)) + ' chars)' if gestalt else 'NO'}")
        print(f"  Personality:  {personality_name or 'NONE'}")
        if personality_wisdom:
            print(f"    Wisdom files: {len(personality_wisdom)} loaded")
        print(f"  Role:         {prefs.get('role') or 'NONE'}")
        if role_wisdom:
            print(f"    Wisdom files: {len(role_wisdom)} loaded")
        print(f"  Project:      {prefs.get('project') or 'NONE'}")
        print(f"  Team members: {len(team)} found")
        print(f"  System prompt: {len(system_prompt)} chars")
        if seed:
            print(f"  Workspace:    would seed at instances/{instance_id}/openfang/workspaces/{agent_name}/")
        return True

    # Write files
    openfang_dir = INSTANCES_DIR / instance_id / "openfang"
    agent_dir = openfang_dir / "agents" / agent_name

    agent_dir.mkdir(parents=True, exist_ok=True)

    if not identity_only:
        config_path = openfang_dir / "config.toml"
        config_path.write_text(config_content)
        print(f"  Written: {config_path}")

    agent_path = agent_dir / "agent.toml"
    agent_path.write_text(agent_content)
    print(f"  Written: {agent_path}")

    # Seed workspace
    if seed:
        ws_dir = seed_workspace(instance_id, prefs, gestalt, personality_json)
        print(f"  Seeded:  {ws_dir}")

    # Summary
    print(f"\n  Instance: {name} ({instance_id})")
    if not identity_only:
        print(f"  Port:     {port}")
    print(f"  Agent:    {agent_name}")
    print(f"  Prompt:   {len(system_prompt)} chars")
    sources = []
    if gestalt:
        sources.append("gestalt")
    if personality_wisdom:
        sources.append(f"personality ({len(personality_wisdom)} wisdom files)")
    if role_wisdom:
        sources.append(f"role ({len(role_wisdom)} wisdom files)")
    print(f"  Sources:  {', '.join(sources) if sources else 'minimal (no gestalt or personality)'}")

    if not identity_only:
        print(f"\n  Next steps:")
        print(f"    1. cp /mnt/.secrets/zeroclaw.env {openfang_dir}/.env")
        print(f"    2. cd {openfang_dir} && source .env && openfang start --config config.toml --daemon")
        print(f"    3. claw-nginx-setup add {instance_id} {port} --type openfang")

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate OpenFang configuration from HACS instance identity data"
    )
    parser.add_argument(
        "--instance", "-i",
        action="append",
        required=True,
        help="HACS instance ID (can specify multiple times)"
    )
    parser.add_argument(
        "--port", "-p",
        type=int,
        default=None,
        help="Specific port (auto-allocated if not set)"
    )
    parser.add_argument(
        "--dry-run", "-n",
        action="store_true",
        help="Show what would be generated without writing files"
    )
    parser.add_argument(
        "--identity-only",
        action="store_true",
        help="Regenerate agent.toml only (skip config.toml)"
    )
    parser.add_argument(
        "--no-seed",
        action="store_true",
        help="Skip workspace seeding"
    )

    args = parser.parse_args()

    if args.port and len(args.instance) > 1:
        print("ERROR: --port can only be used with a single instance", file=sys.stderr)
        sys.exit(1)

    success = True
    for instance_id in args.instance:
        print(f"\n{'=' * 60}")
        print(f"Configuring: {instance_id}")
        print(f"{'=' * 60}")
        ok = configure_instance(
            instance_id,
            port=args.port,
            dry_run=args.dry_run,
            identity_only=args.identity_only,
            seed=not args.no_seed,
        )
        if not ok:
            success = False

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
